[package]
name = "oak_abi"
version = "0.1.0"
authors = ["David Drysdale <drysdale@google.com>"]
edition = "2018"
license = "Apache-2.0"

[features]
std = ["protobuf"]
no_std = []
default = ["std"]

[dependencies]
protobuf = { version = "*", optional = true }

[build-dependencies]
oak_utils = "*"
protoc-rust = "*"
