[package]
name = "oak_platform"
version = "0.1.0"
authors = ["Ben Blaxill <benblaxill@google.com>"]
edition = "2018"

[lib]
name = "oak_platform"

[features]
default = ["std"]
std = []
no_std = []
asylo = ["oak_platform_asylo", "no_std"]

[dependencies]
oak_platform_asylo = { version = "=0.1.0", optional = true }
