[package]
name = "oak_platform_asylo"
version = "0.1.0"
authors = ["Ben Blaxill <benblaxill@google.com>"]
edition = "2018"

[lib]
name = "oak_platform_asylo"
test = false
bench = false

[dependencies]
libc = { version = "*" }
rust_asylo = { version = "=0.1.0", path = "../../../../third_party/rust/src/libstd" }

# We are currently running `cargo test --all-targets` on the workspace root.
# This causes oak_platform_asylo and third_party/rust to try to build test,
# which links in rust stdlib when building. This fails as these crates provide
# e.g. duplicate allocators.
[workspace]
