[package]
name = "oak_platform_asylo"
version = "0.1.0"
authors = ["Ben Blaxill <benblaxill@google.com>"]
edition = "2018"

[lib]
name = "oak_platform_asylo"

[dependencies]
libc = { version = "*" }
rust_asylo = { path = "../../../../third_party/rust/src/libstd" }
