[package]
name = "asylo_rust"
version = "0.1.0"
authors = ["Ben Blaxill <benblaxill@google.com>"]
edition = "2018"

[lib]
name = "asylo_rust"

[dependencies]
libc = "*"
rust = { path = "../../third_party/rust/src/libstd" }
